---
title: "lab04"
author: "Stefany Reis"
format: typst
editor: visual
---

```{r}

# Q1

library(readxl)
library(tidyverse)
```

```{r}

# Q2

fname <- "WDIEXCEL.xlsx"

file.exists(fname)
```

```{r}

# Q3

countries <- read_excel(
  fname,
  sheet = "Country"
)

countries
```
```{r}
glimpse(countries)
```
```{r}
countries %>%
  select(`Short Name`, `Country Code`)
```

```{r}

# Q4

countries <- countries %>%
  filter(
    `Short Name` %in% c(
      "Brazil",
      "Argentina",
      "Chile",
      "Mexico",
      "United States"
    )
  )
```

```{r}

# Q5

WDI <- read_excel(
  fname,
  sheet = "Data"
)
```

```{r}
glimpse(WDI)
```

```{r}

# Q6

WDI <- WDI %>%
  select(
    `Country Code`,
    `Indicator Code`,
    `1960`:`2018`
  )
```

```{r}

# Q7

WDI <- WDI %>%
  pivot_longer(               #coloca em formato tidy
    cols = `1960`:`2018`,
    names_to = "YEAR",
    values_to = "VALUE"
  )
```

```{r}
head(WDI)
```

```{r}

# Q8

WDI <- WDI %>%
  mutate(
    YEAR = as.integer(YEAR)
  )

class(WDI$YEAR)
str(WDI$YEAR)
```
```{r}

# Q9

WDI <- WDI %>%
  semi_join(
    countries,
    by = "Country Code"
  ) %>%
  left_join(
    countries %>%
      select(
        `Country Code`,
        `Short Name`
      ),
    by = "Country Code"
  ) %>%
  filter(
    `Indicator Code` == "SP.DYN.CBRT.IN"
  ) %>%
  select(
    `Country Code`,
    `Short Name`,
    YEAR,
    `VALUE`
  ) %>%
  rename(
    `SP.DYN.CBRT.IN` = VALUE
  )
```


```{r}

# Q10

WDI <- WDI %>%
  arrange(
    `Country Code`,
    YEAR
  )

```


```{r}

# Q11 

ggplot(
  WDI,
  aes(
    x = YEAR,
    y = `SP.DYN.CBRT.IN`,
    color = `Short Name`,
    group = `Short Name`
  )
) +
  geom_line() +
  labs(
    x = "Ano",
    y = "Taxa bruta de natalidade",
    color = "País"
  ) +
  theme_minimal()
```
```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()

```

